### ISSUE TITLE
Doesn't stop timer when switching to another tab

### ISSUE THREAD

**Issue by MarkTiedemann** [remvze/nothing#2]
Perhaps [`onblur`](https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event), the timer should be reset.

**Comment by millette** [comment]
The timer reset for me.

**Comment by MarkTiedemann** [comment]
To reproduce, go to https://usenothing.com/, wait for a few seconds, click `ctrl + t` to create a new tab, wait a few seconds, return to https://usenothing.com/'s tab - time has continued. Tested in both Firefox and Edge on Windows.

**Comment by millette** [comment]
@MarkTiedemann hmm, this time, the timer stopped at 9s and continued from 9s when I returned. It's not an easy problem to fix, I had to deal with times and browser states in another project.

**Comment by remvze** [comment]
Thank you for reporting. Fixed it.

> the timer stopped at 9s and continued from 9s when I returned.

@millette When I created the first version of Nothing, the timer wouldn’t reset on interaction; in fact, it was persisted using local storage. The only change I made was to stop the timer when the tab was changed and resume it when it was back. So, that was intentional and not a bug, but I forgot to change it after adding the "reset" feature.

Now, I've changed it so that it will reset the timer when the page loses focus.
